# Generated by Django 4.0.4 on 2022-06-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_image_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='summary',
        ),
    ]
