# Generated by Django 4.0.4 on 2022-06-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (6, '6')], default=1),
        ),
    ]
