# Generated by Django 4.0.4 on 2022-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
